{% set name = "audio-separator" %}
{% set version = "0.31.0" %}

{% set cuda_enabled = false %}
{% set cuda_enabled = cuda_compiler_version != "None" %}  # [linux64]
{% set build_ext = "cuda" if cuda_enabled else "cpu" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/audio_separator-{{ version }}.tar.gz
  sha256: 4e5dc38fff892c632fb662f612415ecffd15d1e6c981dcf8f8558a5aa40f376c

build:
  number: 0
  noarch: python
  string: {{ build_ext }}
  entry_points:
    - audio-separator = audio_separator.utils.cli:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    # this adds matching cuda requirement to pytorch using __cuda package
    - {{ compiler('cuda') }}  # [linux64 and cuda_compiler_version != "None"]
  host:
    - python >=3.9
    - poetry-core
    - pip
  run:
    - python >=3.9
    - requests >=2
    - numpy >=1.23
    - librosa >=0.10
    - six >=1.16
    - pydub >=0.25
    - pytorch
    - ffmpeg >=6
    - onnx >=1.14
    - onnxruntime =*=*{{ build_ext }}
    - onnx2torch
    - tqdm

test:
  imports:
    - audio_separator
  commands:
    - audio-separator --help
  requires:
    - pip

about:
  home: https://github.com/karaokenerds/python-audio-separator
  summary: Easy to use vocal separation on CLI or as a python package, using the amazing MDX-Net models from UVR trained by @Anjok07
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - beveradb
